//! GraphGlot cross-validation: GQL conformance tests.
//!
//! Reads a corpus of GQL queries generated by GraphGlot (ISO/IEC 39075:2024
//! reference parser) and validates them against Grafeo's GQL parser.
//!
//! The corpus JSON is produced by `tests/graphglot/generate_corpus.py`.
//!
//! ## Test categories
//!
//! Each query is classified into one of four buckets:
//! - **both_pass**: both parsers accept the query (ideal for GQL-standard queries)
//! - **both_fail**: neither parser accepts (malformed queries)
//! - **grafeo_only**: Grafeo parses but GraphGlot rejects (Cypher extensions / superset)
//! - **graphglot_only**: GraphGlot parses but Grafeo rejects (conformance gaps to fix)
//!
//! The `graphglot_only` bucket is the interesting one: these are valid GQL queries
//! that Grafeo does not yet parse correctly.

#[cfg(feature = "gql")]
mod tests {
    use serde::Deserialize;
    use std::path::PathBuf;

    #[derive(Debug, Deserialize)]
    struct Corpus {
        queries: Vec<QueryEntry>,
    }

    #[derive(Debug, Deserialize)]
    struct QueryEntry {
        id: String,
        category: String,
        query: String,
        graphglot_success: bool,
        graphglot_normalized: Option<String>,
        #[allow(dead_code)]
        graphglot_error: Option<String>,
        #[serde(default)]
        graphglot_features: Vec<String>,
        #[allow(dead_code)]
        graphglot_ast_type: Option<String>,
    }

    /// Result bucket for a single query.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum Bucket {
        BothPass,
        BothFail,
        GrafeoOnly,
        GraphglotOnly,
    }

    fn corpus_path() -> PathBuf {
        let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        // Navigate up to workspace root: crates/grafeo-adapters -> grafeo
        path.pop();
        path.pop();
        path.push("tests");
        path.push("graphglot");
        path.push("corpus.json");
        path
    }

    fn load_corpus() -> Corpus {
        let path = corpus_path();
        assert!(
            path.exists(),
            "Corpus file not found at {}. Run: python tests/graphglot/generate_corpus.py",
            path.display()
        );
        let data = std::fs::read_to_string(&path).expect("Failed to read corpus.json");
        serde_json::from_str(&data).expect("Failed to parse corpus.json")
    }

    fn classify(entry: &QueryEntry) -> (Bucket, Option<String>) {
        let grafeo_result = grafeo_adapters::query::gql::parse(&entry.query);
        let grafeo_ok = grafeo_result.is_ok();
        let grafeo_err = grafeo_result.err().map(|e| format!("{e}"));

        let bucket = match (grafeo_ok, entry.graphglot_success) {
            (true, true) => Bucket::BothPass,
            (false, false) => Bucket::BothFail,
            (true, false) => Bucket::GrafeoOnly,
            (false, true) => Bucket::GraphglotOnly,
        };

        (bucket, grafeo_err)
    }

    // -----------------------------------------------------------------------
    // Master conformance report
    // -----------------------------------------------------------------------

    #[test]
    fn graphglot_conformance_report() {
        let corpus = load_corpus();

        let mut both_pass = Vec::new();
        let mut both_fail = Vec::new();
        let mut grafeo_only = Vec::new();
        let mut graphglot_only = Vec::new();

        for entry in &corpus.queries {
            let (bucket, grafeo_err) = classify(entry);
            let record = (entry, grafeo_err);
            match bucket {
                Bucket::BothPass => both_pass.push(record),
                Bucket::BothFail => both_fail.push(record),
                Bucket::GrafeoOnly => grafeo_only.push(record),
                Bucket::GraphglotOnly => graphglot_only.push(record),
            }
        }

        let total = corpus.queries.len();

        println!("\n{}", "=".repeat(72));
        println!("  GraphGlot Cross-Validation Report");
        println!("  Corpus: {} queries", total);
        println!("{}", "=".repeat(72));

        println!(
            "\n  Both pass (standard GQL, both agree):  {} ({:.0}%)",
            both_pass.len(),
            both_pass.len() as f64 / total as f64 * 100.0
        );
        println!(
            "  Both fail (expected parse errors):      {} ({:.0}%)",
            both_fail.len(),
            both_fail.len() as f64 / total as f64 * 100.0
        );
        println!(
            "  Grafeo only (Cypher superset):          {} ({:.0}%)",
            grafeo_only.len(),
            grafeo_only.len() as f64 / total as f64 * 100.0
        );
        println!(
            "  GraphGlot only (conformance gaps):      {} ({:.0}%)",
            graphglot_only.len(),
            graphglot_only.len() as f64 / total as f64 * 100.0
        );

        // Detail: both fail
        if !both_fail.is_empty() {
            println!("\n{}", "-".repeat(72));
            println!("  BOTH FAIL (neither parser accepts):");
            println!("{}", "-".repeat(72));
            for (entry, grafeo_err) in &both_fail {
                println!("  [{}] {}", entry.id, entry.category);
                println!("    Query: {}", entry.query);
                if let Some(err) = grafeo_err {
                    println!("    Grafeo error: {err}");
                }
                if let Some(ge) = &entry.graphglot_error {
                    println!("    GraphGlot error: {ge}");
                }
                println!();
            }
        }

        // Detail: conformance gaps (these are the ones to fix)
        if !graphglot_only.is_empty() {
            println!("\n{}", "-".repeat(72));
            println!("  CONFORMANCE GAPS (GraphGlot parses, Grafeo fails):");
            println!("{}", "-".repeat(72));
            for (entry, grafeo_err) in &graphglot_only {
                println!("  [{}] {}", entry.id, entry.category);
                println!("    Query: {}", entry.query);
                if let Some(err) = grafeo_err {
                    println!("    Grafeo error: {err}");
                }
                if let Some(normalized) = &entry.graphglot_normalized {
                    println!("    GraphGlot normalized: {normalized}");
                }
                if !entry.graphglot_features.is_empty() {
                    println!("    GQL features: {}", entry.graphglot_features.join(", "));
                }
                println!();
            }
        }

        // Detail: Grafeo superset (Cypher extensions)
        if !grafeo_only.is_empty() {
            println!("{}", "-".repeat(72));
            println!("  CYPHER SUPERSET (Grafeo parses, GraphGlot rejects):");
            println!("{}", "-".repeat(72));
            for (entry, _) in &grafeo_only {
                println!("  [{}] {} :: {}", entry.id, entry.category, entry.query);
            }
            println!();
        }

        // Round-trip check: for both_pass entries, verify Grafeo can also
        // parse GraphGlot's normalized form (if different from original).
        let mut roundtrip_ok = 0;
        let mut roundtrip_fail = Vec::new();
        for (entry, _) in &both_pass {
            if let Some(normalized) = &entry.graphglot_normalized {
                let trimmed = normalized.trim();
                if trimmed != entry.query.trim() {
                    match grafeo_adapters::query::gql::parse(trimmed) {
                        Ok(_) => roundtrip_ok += 1,
                        Err(e) => roundtrip_fail.push((entry, trimmed.to_string(), e)),
                    }
                }
            }
        }

        if !roundtrip_fail.is_empty() {
            println!("{}", "-".repeat(72));
            println!("  ROUND-TRIP FAILURES (Grafeo can't parse GraphGlot's normalized form):");
            println!("{}", "-".repeat(72));
            for (entry, normalized, err) in &roundtrip_fail {
                println!("  [{}] {}", entry.id, entry.category);
                println!("    Original:   {}", entry.query);
                println!("    Normalized: {normalized}");
                println!("    Error: {err}");
                println!();
            }
        }

        println!("{}", "=".repeat(72));
        println!(
            "  Round-trip (normalized form): {} OK, {} FAIL",
            roundtrip_ok,
            roundtrip_fail.len()
        );
        println!("{}", "=".repeat(72));

        // The test passes as a report; the assertion below can be enabled
        // once all conformance gaps are closed.
        // assert!(graphglot_only.is_empty(), "Conformance gaps remain");
    }

    // -----------------------------------------------------------------------
    // Per-category tests: each asserts on the specific queries in its category
    // -----------------------------------------------------------------------

    /// Helper: asserts all queries that GraphGlot accepts in a given category
    /// also parse successfully in Grafeo.
    fn assert_category(corpus: &Corpus, category: &str) {
        let entries: Vec<_> = corpus
            .queries
            .iter()
            .filter(|e| e.category == category && e.graphglot_success)
            .collect();

        if entries.is_empty() {
            // No GraphGlot-passing queries in this category (all Grafeo-only / Cypher superset).
            return;
        }

        let mut failures = Vec::new();
        for entry in &entries {
            if let Err(e) = grafeo_adapters::query::gql::parse(&entry.query) {
                failures.push(format!("[{}] {}\n  Error: {e}", entry.id, entry.query));
            }
        }

        assert!(
            failures.is_empty(),
            "Grafeo failed to parse {}/{} GraphGlot-valid queries in '{category}':\n{}",
            failures.len(),
            entries.len(),
            failures.join("\n")
        );
    }

    #[test]
    fn gql_match_basic() {
        assert_category(&load_corpus(), "match_basic");
    }

    #[test]
    fn gql_label_expressions() {
        assert_category(&load_corpus(), "label_expression");
    }

    #[test]
    fn gql_edge_patterns() {
        assert_category(&load_corpus(), "edge_patterns");
    }

    #[test]
    fn gql_quantified_paths() {
        assert_category(&load_corpus(), "quantified_paths");
    }

    #[test]
    fn gql_path_modes() {
        assert_category(&load_corpus(), "path_modes");
    }

    #[test]
    fn gql_path_search() {
        assert_category(&load_corpus(), "path_search");
    }

    #[test]
    fn gql_match_modes() {
        assert_category(&load_corpus(), "match_modes");
    }

    #[test]
    fn gql_named_paths() {
        assert_category(&load_corpus(), "named_paths");
    }

    #[test]
    fn gql_where_clause() {
        assert_category(&load_corpus(), "where_clause");
    }

    #[test]
    fn gql_inline_where() {
        assert_category(&load_corpus(), "inline_where");
    }

    #[test]
    fn gql_return_clause() {
        assert_category(&load_corpus(), "return_clause");
    }

    #[test]
    fn gql_aggregation() {
        assert_category(&load_corpus(), "aggregation");
    }

    #[test]
    fn gql_unwind_for() {
        assert_category(&load_corpus(), "unwind_for");
    }

    #[test]
    fn gql_data_modification() {
        assert_category(&load_corpus(), "data_modification");
    }

    #[test]
    fn gql_composite_queries() {
        assert_category(&load_corpus(), "composite_queries");
    }

    #[test]
    fn gql_subqueries() {
        assert_category(&load_corpus(), "subqueries");
    }

    #[test]
    fn gql_expressions() {
        assert_category(&load_corpus(), "expressions");
    }

    #[test]
    fn gql_type_cast() {
        assert_category(&load_corpus(), "type_cast");
    }

    #[test]
    fn gql_temporal() {
        assert_category(&load_corpus(), "temporal");
    }

    #[test]
    fn gql_string_functions() {
        assert_category(&load_corpus(), "string_functions");
    }

    #[test]
    fn gql_numeric_functions() {
        assert_category(&load_corpus(), "numeric_functions");
    }

    #[test]
    fn gql_parameters() {
        assert_category(&load_corpus(), "parameters");
    }

    #[test]
    fn gql_session_commands() {
        assert_category(&load_corpus(), "session_commands");
    }

    #[test]
    fn gql_transaction_commands() {
        assert_category(&load_corpus(), "transaction_commands");
    }

    #[test]
    fn gql_schema_ddl() {
        assert_category(&load_corpus(), "schema_ddl");
    }

    #[test]
    fn gql_graph_type_ddl() {
        assert_category(&load_corpus(), "graph_type_ddl");
    }

    #[test]
    fn gql_filter_statement() {
        assert_category(&load_corpus(), "filter_statement");
    }

    #[test]
    fn gql_let_bindings() {
        assert_category(&load_corpus(), "let_bindings");
    }

    #[test]
    fn gql_select_statement() {
        assert_category(&load_corpus(), "select_statement");
    }

    #[test]
    fn gql_literals() {
        assert_category(&load_corpus(), "literals");
    }

    #[test]
    fn gql_predicates() {
        assert_category(&load_corpus(), "predicates");
    }

    #[test]
    fn gql_path_alternation() {
        assert_category(&load_corpus(), "path_alternation");
    }

    #[test]
    fn gql_complex_queries() {
        assert_category(&load_corpus(), "complex_queries");
    }

    #[test]
    fn gql_optional_blocks() {
        assert_category(&load_corpus(), "optional_blocks");
    }

    #[test]
    fn gql_savepoints() {
        assert_category(&load_corpus(), "savepoints");
    }
}
